### ISSUE TITLE
Support AWS configuration

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#116]

**Comment by lwander** [comment]
The linked PRs & details in https://github.com/spinnaker/halyard/issues/71 will be helpful.

There is an additional requirement to support front50 config - see https://github.com/spinnaker/halyard/issues/106

**Comment by lwander** [comment]
The clouddriver config & cli commands are added by #146

**Comment by lwander** [comment]
Here's the remaining work:

1. Validate your AWS account by extending [this](https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/aws/AwsAccountValidator.java).
2. Configure your rosco images. This https://github.com/spinnaker/halyard/pull/147 does a good job of showing how that can be done. Note, I don't have the story figured out yet for dealiing with template files, and overriding base images - that'll come later.
3. [Configure settings.js](https://github.com/spinnaker/halyard/blob/master/docs/adding-a-provider.md#5-update-settingsjs).
4. Validate Front50 S3 config. This https://github.com/spinnaker/halyard/pull/189 gets the job started, but I'm not sure how Front50 deals with credentials.

**Comment by lwander** [comment]
@gardleopard

**Comment by lwander** [comment]
@gardleopard following our convo this morning:

```bash
hal config provider aws account add --<some parameters>
hal config provider aws enable
hal config storage aws edit --<some other parameters>
hal config storage edit --type aws

hal deploy edit --type localdebian
sudo hal deploy apply
```

is the minimal set of commands that should be needed to configure & deploy to aws.

**Comment by gardleopard** [comment]
@lwander `hal config storage aws edit --<some other parameters>` should be `s/aws/s3/g` right?

**Comment by lwander** [comment]
ah yes, that's right, sorry about that. I'll edit the above message

**Comment by lwander** [comment]
Closing this in favor of a more descriptive bug.

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/issues/537
