### ISSUE TITLE
Support OpenStack configuration

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#117]
The linked PRs & details in #71 will be helpful.

**Comment by emjburns** [comment]
@lwander are you targeting this for the April release? When are you looking for other providers to start adding support?

**Comment by lwander** [comment]
Hey @emjburns - I'm going to walk you guys through this work in the slack room. I didn't expect you guys to find this issue already ;)

April release would be ideal. This is a fairly small chunk of work, it just requires some familiarity with the existing openstack config.

**Comment by emjburns** [comment]
Oops should be able to close this because of https://github.com/spinnaker/halyard/pull/192

**Comment by lwander** [comment]
:+1:
