### ISSUE TITLE
Support CloudFoundry configuration

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#118]
The linked PRs & details in #71 will be helpful.

**Comment by mainephd** [comment]
@lwander  Should this be working with the latest version of Halyard to manage spinnaker? I am getting the below error when I try to enable the cloud foundry provider

```
$ hal config
- Get current deployment
  Failure
Problems in Global:
! ERROR Could not translate your halconfig: Unrecognized field "cf"
  (class com.netflix.spinnaker.halyard.config.model.v1.node.Providers), not marked
  as ignorable (9 known properties: "appengine", "kubernetes", "google", "aws",
  "openstack", "azure", "dcos", "oraclebmcs", "dockerRegistry"])
at [Source: N/A; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["providers"]->com.netflix.spinnaker.halyard.config.model.v1.node.Providers["cf"])
$ hal --version
0.34.0-20170901142041
```

**Comment by lwander** [comment]
Cloud foundry isn't a supported provider by Spinnaker anymore. If you or anyone else wants to pick up the work to finish the provider & add halyard support we'll be happy to help guide you through it.

**Comment by mainephd** [comment]
that would be cool. I would be interested in picking it up. Where can I go to get up to speed on what needs to happen? @lwander

**Comment by lwander** [comment]
That's great :) I would start by pinging the #dev channel on join.spinnaker.io
