### ISSUE TITLE
Generate Echo Config

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#178]
The focus here will be configuring notifications (e.g. sms, slack, email...).

**Comment by joesenova** [comment]
Currently dealing with this Issuer here::

https://github.com/spinnaker/halyard/pull/562

**Comment by psyhomb** [comment]
Right now only slack notification service is supported through hal is there any chance to implement email service as well?

Thanks

**Comment by lwander** [comment]
Yup, the configuration is straight-forward to add to Halyard. I don't have
time in the near future, but anyone is welcome to jump in and try.
