### ISSUE TITLE
Scope out Single-VM Halyard Spinnaker Deployment on GCE

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#225]
Before doing this, we need to decide on the following:

1. If VMs are baked by the user of Spinnaker.
2. How config is sent to the VM.
3. How secrets are sent to the VM.
4. If updates can be done via Red/Black.

**Comment by lwander** [comment]
1, 2, and 3 are addressed in https://github.com/spinnaker/halyard/pull/266.
4. Seems impractical given the nuances described in https://github.com/spinnaker/halyard/pull/266

**Comment by lwander** [comment]
Given that the only additional work required to go from single to multi vm is the addition of Consul, and per-service VM images, I'd prefer to work directly toward having a multi-vm deployment given the time, @skim1420.

**Comment by skim1420** [comment]
sgtm. See my comments in [#266](https://github.com/spinnaker/halyard/pull/266)
