### ISSUE TITLE
Support ability to shutdown and/or restart Halyard daemon

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/halyard#241]
Would be nice if `hal` supported it directly, but indirectly, I'd suggest enabling the shutdown endpoint:

halyard.yml
```
endpoints.shutdown.enabled: true
```
We have scripts to do this for other Spinnaker services, but not Halyard (to my knowledge).

**Comment by lwander** [comment]
Oh neat, that config enables which endpoint?

**Comment by ttomsu** [comment]
I believe it enables `/shutdown`. Not sure if it needs to be a POST or if a simple GET will do.

**Comment by lwander** [comment]
I added the config flag here: https://github.com/spinnaker/halyard/pull/250 I'm keeping it out of hal for now since it makes it a little easy to shoot yourself in the foot.
