### ISSUE TITLE
Show top-level Spinnaker version # in UI

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#275]
I'm thinking we could add a feature-flag in settings.js that Halyard writes, and shows up in the top navbar. WDYT @danielpeach?

**Comment by danielpeach** [comment]
That sounds cool. If you write the flag, I'll add it to Deck.

**Comment by lwander** [comment]
:sunglasses:

**Comment by lwander** [comment]
WDYT? https://github.com/spinnaker/deck/pull/3449

**Comment by lwander** [comment]
How is the deck side of this going @danielpeach?
