### ISSUE TITLE
Halyard can't be installed on Ubuntu 16.04

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#279]

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker-gradle-project/pull/30

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/609

**Comment by ctompkinson** [comment]
@Iwander Hows the progress of this? and are you looking for contributors to speed this along?

**Comment by lwander** [comment]
Hey - it can be - 
```bash
curl https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh && sudo bash InstallHalyard.sh
```
 will work fine. The issue is that the rest of Spinnaker can't be installed on 16.04 yet. Fixing this will require (what should be a simple) flag added to the debian builds here: https://github.com/spinnaker/spinnaker/blob/master/dev/build_release.py, but that script is more complicated than it should be...

**Comment by driv3r** [comment]
in 6 months there will be another LTS release

**Comment by psyhomb** [comment]
> The issue is that the rest of Spinnaker can't be installed on 16.04 yet

Anything new on this, I mean when we can expect full Spinnaker support for 16.04?

**Comment by jtk54** [comment]
This is an active work item currently, hopefully landing soon.

**Comment by lwander** [comment]
https://www.spinnaker.io/setup/install/halyard/
