### ISSUE TITLE
Version "latest" is not a released (validated) version of Spinnaker

### ISSUE THREAD

**Issue by idoshamun** [spinnaker/halyard#281]
Running `hal config version edit --version latest`, throws the following error:
```
- Validating default with DeploymentConfigurationValidator
Problems in default: 
- WARNING Version "nightly" is not a released (validated) version
  of Spinnaker.
? Options include: 
  - 0.1.0
  - 0.2.0
```

The same issue happens with `nightly`

**Comment by lwander** [comment]
This is intentional, since neither of those releases are validated. And since it's a warning it doesn't prevent a deployment from happening.
