### ISSUE TITLE
Allow users to manually specify UI & API BaseUrls

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#286]
The assumption is that users who have their own infrastructure to front Gate & Deck won't want Spinnaker to provision it for them.

**Comment by lwander** [comment]
@idoshamun FYI

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/324

**Comment by idoshamun** [comment]
Waited for it! thanks :)

**Comment by lwander** [comment]
Sorry for the wait - there have also been a few schema changes in the halconfig since you last downloaded halyard, ping me on Slack if run into trouble.

**Comment by idoshamun** [comment]
I'll give it a shot and let you know
