### ISSUE TITLE
KMS for halconfig

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#417]
It would be convenient to avoid coupling halyard to one specific filesystem, and instead allow users to point at a remote encrypted repo containing everything halyard needs to deploy a specific instance of Spinnaker.

**Comment by jmaclabs** [comment]
If possible can hal backup extend to pack and rewrite halconfig to make it easy to move between machines (when no KMS is configured)?

**Comment by lwander** [comment]
Given that `hal backup create` provides a solution for users to move halconfigs between machines (& dependent files) I'm closing this for now, leaving encryption up to users.
