### ISSUE TITLE
Force cache refresh throws 403 when authz is enabled

### ISSUE THREAD

**Issue by idoshamun** [spinnaker/halyard#434]
I am running halyard 0.13.0-336 and when enabling authz the deployment fails due to access denied error while trying to force cache refresh

**Comment by lwander** [comment]
@ttomsu can you have a look at this?

**Comment by lwander** [comment]
Closed by: https://github.com/spinnaker/halyard/pull/445

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/496 (Sorry, finally confident that fixes the problem you were seeing). It's released in Halyard stable 0.17.0
