### ISSUE TITLE
Authentication is disabled

### ISSUE THREAD

**Issue by idoshamun** [spinnaker/halyard#435]
I am using halyard 0.13.0-336 and when enabling google provider authentication, spinnaker still allows anonymous access

**Comment by lwander** [comment]
@ttomsu can you have a look at this?

**Comment by ttomsu** [comment]
I'm going to need way more information to properly diagnose. Please ping me in the Spinnaker #spin-auth channel on Slack: http://join.spinnaker.io/

**Comment by lwander** [comment]
Hey sorry for the wait @idoshamun - how did you determine that anonymous access works? We tried to replicate but can't access Spinnaker anonymously.

**Comment by idoshamun** [comment]
I just enter to Spinnaker homepage and it allows to use it without login and at the top right corner it says "anonymous"

**Comment by lwander** [comment]
Could you share some more of how you set up authn? It's likely a configuration problem & we want to make sure Halyard validates properly

**Comment by idoshamun** [comment]
I have just updated Halyard to the latest version and deployed again, but now something with the redirection of the authentication is broken. Still trying to figure exactly what it is

**Comment by lwander** [comment]
Hey @idoshamun did adjusting the fiat service account fix this?

**Comment by idoshamun** [comment]
Yes, sorry forgot about this issue
