### ISSUE TITLE
Suggestion for doc improvement for hal docker registry parameters

### ISSUE THREAD

**Issue by jmaclabs** [spinnaker/halyard#522]
Hello, 

Whilst setting up spinnaker using halyard and minikube, I ran into some pain while registering my docker-registry. 

The base command is: 
`hal config provider docker-registry account add `

..and it requires additional parameters to be provided.

For value for the `--address` parameter does not require the protocol prefix (e.g. https://), only the FQDN address (e.g. `--address=index.docker.io`) for the command to work.

The value for the `--repositories` param for the new Docker Cloud repos requires the account username and repo name (e.g. `--repositories=username/repo_name`) for the command to work.

I spent more time than I'd like to admit trying to figure that second one out - a little more context in the doc might save some one from getting stuck on that.

**Comment by lwander** [comment]
Ah absolutely - will fix

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker.github.io/pulls
