### ISSUE TITLE
S3 setup example uses incorrect parameter name

### ISSUE THREAD

**Issue by jmaclabs** [spinnaker/halyard#523]
The setup page provides an example for how to setup S3
[https://spinnaker.github.io/setup/storage/s3/](https://spinnaker.github.io/setup/storage/s3/)

The parameter for providing the AWS ID `--secret-key-id` is incorrect.

That page has a link to the commands page, which declares the parameter as `--access-key-id`
[https://spinnaker.github.io/reference/halyard/commands/#hal-config-storage-s3-edit](https://spinnaker.github.io/reference/halyard/commands/#hal-config-storage-s3-edit)

The `--access-key-id` is correct and works for setting up an AWS S3 storage

**Comment by lwander** [comment]
Good catch - will fix - thank you :)

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker.github.io/commit/5bcd468f14207cf91be3026b5bd6250ab2a49bb9
