### ISSUE TITLE
Stuck at "Waiting for the Halyard daemon to start running"

### ISSUE THREAD

**Issue by bhardwajankur3** [spinnaker/halyard#539]
While installing it gets stuck for hours at the step "Waiting for the Halyard daemon to start running" and does not proceed. I ran the following the following commands to install it:

curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh

sudo bash InstallHalyard.sh

**Comment by lwander** [comment]
Can you show me your logs in `/var/log/upstart/halyard` as well as `/var/log/spinnaker/halyard/halyard.log`?

**Comment by bhardwajankur3** [comment]
halyard.log is empty. But when I ran this following command: hal --ready. It throws the following error:
! ERROR Failed to connect to localhost/127.0.0.1:8064
? Is your daemon running?

So its stuck in the while loop at the end of InstallHalyard.sh and not coming out of it

**Comment by bhardwajankur3** [comment]
halyard.log under halyard folder is empty. However, halyard.log under upstart folder has the following:
cat: /opt/spinnaker/config/halyard-user: No such file or directory
cat: /opt/spinnaker/config/halyard-user: No such file or directory
sudo: unknown user: -g
sudo: unable to initialize policy plugin
sudo: unknown group: ankbhardwaj
sudo: unable to initialize policy plugin

**Comment by lwander** [comment]
Odd that the /opt/spinnaker/config/halyard-user file wasn't created. Did you see errors during install? Is there a /opt/spinnaker/config/halyard.yml file?

**Comment by lwander** [comment]
The fix is to create the /opt/spinnaker/config/halyard-user file, and then simply enter on a single line the name of the user you want to run halyard as (your current user is recommended).

**Comment by bhardwajankur3** [comment]
I didn't see any error. However, halyard-user and halyard.yml do exist under /opt/spinnaker/config/

**Comment by lwander** [comment]
what are the permissions for the file halyard-user?

**Comment by lwander** [comment]
can you `chmod +r` that file, and then try restarting the daemon?

**Comment by bhardwajankur3** [comment]
Its -rw------- 1 root root 12 Jun  7 13:49 halyard-user

**Comment by lwander** [comment]
ok, in that case definitely run `sudo chmod +r /opt/spinnaker/config/halyard-user` and `sudo service halyard restart`. I'll look into why the permissions are off on this install.

**Comment by bhardwajankur3** [comment]
When I ran sudo service halyard restart. It throws this : stop: Unknown instance: 
halyard start/running, process 3802

**Comment by lwander** [comment]
That's fine, it's because halyard never started so it can't stop it. The command should have started halyard though, you can verify with `hal --ready`.

**Comment by bhardwajankur3** [comment]
I just did. It throws the same error: 
! ERROR Failed to connect to localhost/127.0.0.1:8064
? Is your daemon running?

**Comment by lwander** [comment]
And the logs in those same directories as before?

**Comment by bhardwajankur3** [comment]
Yes. Except that halyard.log under upstart has these appended:
sudo: unknown group: ankbhardwaj
sudo: unable to initialize policy plugin

**Comment by lwander** [comment]
Interesting, what environment are you running these install scripts in?

**Comment by bhardwajankur3** [comment]
Its Ubuntu 14.04 as recommended

**Comment by bhardwajankur3** [comment]
It's a VM on GCP

**Comment by lwander** [comment]
Ok- can you on a fresh VM rerun that installation script, but pass the `-y` parameter like this?
```
sudo bash InstallHalyard.sh -y
```

**Comment by bhardwajankur3** [comment]
Same issue on new VM with the same content in those log files

**Comment by lwander** [comment]
I've tried to reproduce this a few different ways - which exact ubuntu 14.04 image are you using in GCE?

**Comment by bhardwajankur3** [comment]
Ubuntu 14.04 Base Image (Certified by Infosec via RITM0036225) Source: ubuntu-1404-canonical-20170523-disk Feature: Based on Canonical Im

**Comment by lwander** [comment]
Hey - if you're still having trouble can you retry the installation on a fresh VM? The InstallHalyard.sh script has been update.

**Comment by bhardwajankur3** [comment]
Hi! I tried to install it on VM created by public Ubuntu image on GCP. It worked absolutely fine. But Today when I tried to install it on VM created by custom image on my company's GCP. It threw this error: chown: invalid group: ‘ankbhardwaj:ankbhardwaj’. So what I did was I created a group called ankbhardwaj then made ankbhardwaj user belong to this group. Then I tried again. And it worked.

**Comment by lwander** [comment]
Ok - I think I can safely lift the group requirement during the install procedure. Glad to hear it worked though :)

**Comment by bhardwajankur3** [comment]
Thank you so much for your help! I have also joined spinnaker team slack channel. See you there :)

**Comment by lwander** [comment]
Group requirement dropped - see you on slack :)

**Comment by alertedsnake** [comment]
I'm not sure this is fixed, I just ran this myself and have a similar issue:
```
Waiting for the Halyard daemon to start running...............................
Waiting for halyard to start timed out after 123 seconds
~
Install finished with exit code (1)... cleaning up
$ lsb_release -d
Description:	Ubuntu 14.04.5 LTS
```

I can start it manually of course, but probably the installer should work properly.
