### ISSUE TITLE
Can't run halyard behind proxy

### ISSUE THREAD

**Issue by szaher** [spinnaker/halyard#558]
Hi,

I was trying to use halyard behind proxy and it's failing to get versions.yml from google somewhere 

Is there anyway I can pass the proxy information to halyard or how can I download the file and pass it to halyard ?

saad@ubuntu:~$ hal version list
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
- Get released versions
  Failure
Problems in Global:
! ERROR Could not load "versions.yml" from config bucket: Received
  fatal alert: access_denied.

- Failed to load available Spinnaker versions.

Contents of /opt/spinnaker/config/halyard.yml ::
halyard:
  halconfig:
    directory: /home/saad/.hal

spinnaker:
  artifacts:
    debianRepository: https://dl.bintray.com/spinnaker-releases/debians
    dockerRegistry: gcr.io/spinnaker-marketplace
    googleImageProject: marketplace-spinnaker-release

saad@ubuntu:~$ ls  /home/saad/.hal/
uninstall.sh

Contents of /opt/halyard/config/halyard.yml :: 

server:
  port: 8064

halconfig:
  filesystem:
    path: ~/.hal/config

spinnaker:
  artifacts:
    debian: https://dl.bintray.com/spinnaker-releases/debians
    docker: gcr.io/spinnaker-marketplace
  config:
    input:
      writerEnabled: false
      bucket: halconfig

endpoints:
  env:
    sensitive: false
  autoconfig:
    sensitive: false
  resolvedEnv:
    sensitive: false
  beans:
    sensitive: false
  shutdown:
    enabled: true
    sensitive: false

backup:
  google:
    enabled: false

retrofit:
  logLevel: BASIC

security:
  basic:
    enabled: false

part of the log: 
http://paste.openstack.org/show/612444/

Thanks

**Comment by lwander** [comment]
What does the proxy do? Halyard depends on that bucket for canonical configuration for each microservice as well microservice versions.

**Comment by szaher** [comment]
I think halyard is trying to fetch something from the internet, I'm not sure what exactly but I think this is what fails https://github.com/spinnaker/halyard/blob/d325bade0fbded7180882fd45668b228c6a8b8a7/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java#L57 

It's complaining about "versions.yml" .

I'm trying to install halyard behind proxy, so I configured the proxy on my VM and I don't know why halyard is not using it to fetch the file.

**Comment by lwander** [comment]
Halyard will have to fetch many files - ones to configure the services, ones to pick the correct versions, and then ones to install the artifacts (if you're deploying locally).

**Comment by szaher** [comment]
Yes, I'm deploying locally behind proxy. so halyard can't fetch these files. Is there anyway I can configure halyard to use the proxy  ?

**Comment by lwander** [comment]
I think you need to configure the proxy to allow access to the gs://halconfig bucket.

**Comment by szaher** [comment]
Is http_proxy and https_proxy not enough to use those two environment variables to make it work ?

I have control over the proxy so I can't really modify anything

**Comment by lwander** [comment]
Sorry what do those env variables do? If so - can't you set those for the daemon yourself?

**Comment by nfirvine** [comment]
@lwander those env vars typically (by convention) make a process use an HTTP proxy to do all outbound requests. For example, curl uses them: https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

I think the request is failing because halyard's not using the proxy at all. Probably szaher's corporate transparent proxy (not the one he wants to use, but the one that's forced upon him) blocks GCS with a 403

**Comment by lwander** [comment]
Oh thanks for explaining @nfirvine. if either of you would like to contribute, this is where GCS service is instantiated: https://github.com/spinnaker/halyard/blob/master/halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/ProfileRegistry.java

**Comment by nfirvine** [comment]
I don't Java too good, unfortunately ;)

Here's a workaround. Hack your hal script, adding these system properties:
```
java -Dhttp.proxyHost=my.proxy.domain.com -Dhttp.proxyPort=3128
```

Source: https://developers.google.com/gdata/articles/proxy_setup

**Comment by lwander** [comment]
Thank you :) If anyone has the chance to verify I'll add it to the public docs

**Comment by robbinhan** [comment]
@nfirvine It's not work for me

**Comment by szaher** [comment]
@robbinhan It did work for me. you might want to add the https

"-Dhttp.nonProxyHosts=localhost,127.0.0.1" "-Dhttp.proxyHost=proxy.xyz.com" "-Dhttp.proxyPort=8080" "-Dhttps.proxyHost=proxy.xyz.com" "-Dhttps.proxyPort=8080"

**Comment by szaher** [comment]
@nfirvine Thanks :) It did work for me!

**Comment by szaher** [comment]
so the workaround for me was I edited this file /opt/halyard/bin/halyard and I've appended the proxy configurations to this variable DEFAULT_JVM_OPTS

DEFAULT_JVM_OPTS='"-Dhttp.nonProxyHosts=localhost,127.0.0.1,x.y.z.j" "-Dhttp.proxyHost=proxy.xyz.com" "-Dhttp.proxyPort=8080" "-Dhttps.proxyHost=proxy.xyz.com" "-Dhttps.proxyPort=8080" "-Djava.security.egd=file:/dev/./urandom" "-Dspring.config.location=/opt/spinnaker/config/"'

**Comment by robbinhan** [comment]
@szaher You are right. I found where something wrong. I need restart halyard when I changed DEFAULT_JVM_OPTS. Thank you very much.

**Comment by lwander** [comment]
Added to https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-run-halyard-behind-a-proxy.

Thanks for the help!

**Comment by vwyuheng** [comment]
@robbinhan   It's not work for me, please help me, how can i solved it?

**Comment by vwyuheng** [comment]
@robbinhan  I changed DEFAULT_JVM_OPTS and restart halyard,but the proxy is not take effect. what can i to do?
