### ISSUE TITLE
postInstall.sh is using spinnaker as user

### ISSUE THREAD

**Issue by TYsewyn** [spinnaker/halyard#564]
The `postInstall.sh` script should use the current user or given username, not spinnaker.
If the `/var/spinnaker/config/halyard-user` contains the user, you can easily use this file to retrieve the user instead of using spinnaker.

However, this issue should be fixed after #563 since the content of this file is only written after the installation has been completed.

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/572
