### ISSUE TITLE
Have one error for this command:hal config storage edit --type redis

### ISSUE THREAD

**Issue by fionaliupw** [spinnaker/halyard#575]
Hello,When i setup storage(--type redis), i got one error. The error is as following:

Unexpected exception: java.lang.RuntimeException: Failed to
invoke validate() on "DeploymentConfigurationValidator" for node
"DeploymentConfiguration

I hava installed redis, and have updated the halyard, but it don't work. How can i solve this problem? Thank you.

**Comment by anihak** [comment]
i have the same problem with all the "hal config ..." cmds

**Comment by lwander** [comment]
This generally happens when you don't have access to storage.googleapis.com - it's used for validating your chosen version of spinnaker against the config you provide. To be sure, can you rerun with the `--debug` flag and paste the output into a gist?

**Comment by anihak** [comment]
I need to use a proxy to  go outside, but i don't know where I can configure it to halyard in order to get this cmds working . I have already tried to run them in a netwoks that doesn't use proxy,  and they are  working . so I think that if I can use proxy when accessing to (storage.googleapis.com ) I can resolv my problem

**Comment by lwander** [comment]
https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-run-halyard-behind-a-proxy

**Comment by anihak** [comment]
I changed the variable like this      "-Dhttp.proxyHost=139.54.130.250" "-Dhttp.proxyPort=3128" "-Dhttps.proxyHost=139.54.130.250" "-Dhttp.proxyPort=3128" "-Dhttp.noProxyHosts=localhost,127.0.0.1" "-Djava.security.edg=file:/dev/.urandom" "-Dspring.config.location=/opt/spinnaker/config"'   

but now I have this problem : 
! ERROR Failed to connect to localhost/127.0.0.1:8064
? Is your daemon running?
I have seen this link also :https://github.com/spinnaker/halyard/issues/539

**Comment by anihak** [comment]
-Djava.security.edg=file:/dev/./urandom not Djava.security.edg=file:/dev/.urandom

**Comment by anihak** [comment]
I have done a new install, now it is working, 

thank you
