### ISSUE TITLE
Unable to setup spinnaker in service project of GCP (Shared VPC)

### ISSUE THREAD

**Issue by degaglani** [spinnaker/halyard#577]
While executing this command:
hal config provider google account add my-gce-account --project $PROJECT --json-path $SERVICE_ACCOUNT_DEST

Error:
- Add the my-gce-account account
 Failure
Problems in default.provider.google:
! ERROR Network gcp-test-network not found via any
 configured google account.

Changing network:
hal config provider google bakery edit --network gcp-test-network

This network has 2 subnets.  How to specify subnets?

**Comment by lwander** [comment]
Hey, just curious, why do you want to specify the subnet here? I think this needs to be done with a custom rosco template: https://www.spinnaker.io/setup/bakery/#packer-templates

WDYT @duftler?

**Comment by degaglani** [comment]
Hi.. my main issue was spinnaker unable to detect shared network.  How do I resolve this?

**Comment by anandpalanisamy** [comment]
Hi Lars,

If I am not mistaken, the packer-templates comes into picture after Spinnaker set up is complete using Halyard. Devang is stuck with setting up Spinnaker itself with xpn shared network.

**Comment by lwander** [comment]
Oh I see - the network he's editing is used by the service that consumes those packer templates, so I figured that was the intent here. @duftler and I are taking a second look at the XPN permissions.

**Comment by duftler** [comment]
There is a new 'network_project_id' attribute defined on the packer google builder. This pr adds support for it to rosco: https://github.com/spinnaker/rosco/pull/212

**Comment by duftler** [comment]
Adds support for this new bakery attribute to halyard: https://github.com/spinnaker/halyard/pull/587

**Comment by anandpalanisamy** [comment]
@duftler @lwander appreciate the quick fix on this.

**Comment by duftler** [comment]
The 2 PRs are merged. Working on releases now.

**Comment by duftler** [comment]
These changes were released yesterday in the latest versions of Spinnaker (https://www.spinnaker.io/community/releases/versions/#version-110) and Halyard (0.29.0-10).
