### ISSUE TITLE
Make custom spinnaker repository easier.

### ISSUE THREAD

**Issue by eisig** [spinnaker/halyard#581]
Make custom spinnaker repository easier, and  ProfileRegistry storage backend configureable.

I would like to customer the REPOSITORY_URL in /home/ubuntu/.hal/default/install.sh. 
But the config   "spinnaker.artifacts.debianRepository" in /opt/spinnaker/config/halyard.yml   would be override by the value in the bom.
I try to use "hal admin publish bom", but it use google storage, thoug I am using spinnaker in AWS.
What is worse, Google service is block by the GFW in China.

**Comment by lwander** [comment]
This is done intentionally to make is easier for us to migrate between repositories/docker image sources. You will have to provide support for loading BOMs from disk, rather than GCS. I'll open an issue that reflects this.

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/issues/582
