### ISSUE TITLE
Halyard backup fails due to unclosed entries

### ISSUE THREAD

**Issue by bggpoort** [spinnaker/halyard#590]
I'm trying to create a backup of the current Spinnaker configuration, but for some reason this fails. Current situation is Halyard version 0.29.0-10 with Spinnaker version 1.1.0, but I was able to reproduce with Spinnaker version 1.0.1 and Halyard versions 0.28.0-9 and 0.27.0-8.

Debug output of the backup command:

`---> HTTP PUT http://localhost:8064/v1/backup/create
Content-Type: application/json; charset=UTF-8
Content-Length: 2
""
---> END HTTP (2-byte body)
<--- HTTP 200 http://localhost:8064/v1/backup/create (192ms)
Server: Apache-Coyote/1.1
X-Application-Context: halyard:test,local:8064
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 06 Jul 2017 13:18:14 GMT
OkHttp-Sent-Millis: 1499347094855
OkHttp-Received-Millis: 1499347094867

{
  "name" : "Create backup",
  "timeout" : 60000,
  "events" : [ ],
  "children" : [ ],
  "uuid" : "5c26ef7b-86ac-4f64-844e-78c08b74d8fa",
  "timedOut" : false,
  "version" : "0.29.0-10",
  "state" : "RUNNING",
  "response" : null,
  "fatalError" : null,
  "runningJobs" : [ ]
}
<--- END HTTP (279-byte body)
---> HTTP GET http://localhost:8064/v1/tasks/5c26ef7b-86ac-4f64-844e-78c08b74d8fa/
---> END HTTP (no body)
<--- HTTP 200 http://localhost:8064/v1/tasks/5c26ef7b-86ac-4f64-844e-78c08b74d8fa/ (4ms)
Server: Apache-Coyote/1.1
X-Application-Context: halyard:test,local:8064
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 06 Jul 2017 13:18:14 GMT
OkHttp-Sent-Millis: 1499347095014
OkHttp-Received-Millis: 1499347095018

{
  "name" : "Create backup",
  "timeout" : 60000,
  "events" : [ ],
  "children" : [ ],
  "uuid" : "5c26ef7b-86ac-4f64-844e-78c08b74d8fa",
  "timedOut" : false,
  "version" : "0.29.0-10",
  "state" : "FAILED",
  "response" : {
    "responseBody" : null,
    "problemSet" : {
      "problems" : [ {
        "message" : "Unable to safely backup halconfig This archives contains unclosed entries.",
        "remediation" : null,
        "options" : null,
        "severity" : "FATAL",
        "location" : "Global"
      } ]
    }
  },
  "fatalError" : {
    "cause" : {
      "cause" : null,
      "stackTrace" : [ {
        "methodName" : "finish",
        "fileName" : "TarArchiveOutputStream.java",
        "lineNumber" : 122,
        "className" : "org.apache.commons.compress.archivers.tar.TarArchiveOutputStream",
        "nativeMethod" : false
      }, {
        "methodName" : "tarHalconfig",
        "fileName" : "BackupService.java",
        "lineNumber" : 143,
        "className" : "com.netflix.spinnaker.halyard.backup.services.v1.BackupService",
        "nativeMethod" : false
      }, {
        "methodName" : "create",
        "fileName" : "BackupService.java",
        "lineNumber" : 77,
        "className" : "com.netflix.spinnaker.halyard.backup.services.v1.BackupService",
        "nativeMethod" : false
      }, {
        "methodName" : "lambda$create$0",
        "fileName" : "BackupController.java",
        "lineNumber" : 46,
        "className" : "com.netflix.spinnaker.halyard.controllers.v1.BackupController",
        "nativeMethod" : false
      }, {
        "methodName" : "build",
        "fileName" : "DaemonResponse.java",
        "lineNumber" : 121,
        "className" : "com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder",
        "nativeMethod" : false
      }, {
        "methodName" : "lambda$submitTask$1",
        "fileName" : "TaskRepository.java",
        "lineNumber" : 48,
        "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository",
        "nativeMethod" : false
      }, {
        "methodName" : "run",
        "fileName" : "Thread.java",
        "lineNumber" : 745,
        "className" : "java.lang.Thread",
        "nativeMethod" : false
      } ],
      "message" : "This archives contains unclosed entries.",
      "localizedMessage" : "This archives contains unclosed entries.",
      "suppressed" : [ ]
    },
    "stackTrace" : [ {
      "methodName" : "create",
      "fileName" : "BackupService.java",
      "lineNumber" : 79,
      "className" : "com.netflix.spinnaker.halyard.backup.services.v1.BackupService",
      "nativeMethod" : false
    }, {
      "methodName" : "lambda$create$0",
      "fileName" : "BackupController.java",
      "lineNumber" : 46,
      "className" : "com.netflix.spinnaker.halyard.controllers.v1.BackupController",
      "nativeMethod" : false
    }, {
      "methodName" : "build",
      "fileName" : "DaemonResponse.java",
      "lineNumber" : 121,
      "className" : "com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder",
      "nativeMethod" : false
    }, {
      "methodName" : "lambda$submitTask$1",
      "fileName" : "TaskRepository.java",
      "lineNumber" : 48,
      "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "Thread.java",
      "lineNumber" : 745,
      "className" : "java.lang.Thread",
      "nativeMethod" : false
    } ],
    "problems" : {
      "problems" : [ {
        "message" : "Unable to safely backup halconfig This archives contains unclosed entries.",
        "remediation" : null,
        "options" : null,
        "severity" : "FATAL",
        "location" : "Global"
      } ]
    },
    "responseCode" : 409,
    "message" : "Unable to safely backup halconfig This archives contains unclosed entries.",
    "localizedMessage" : "Unable to safely backup halconfig This archives contains unclosed entries.",
    "suppressed" : [ ]
  },
  "runningJobs" : [ ]
}
<--- END HTTP (4056-byte body)
- Create backup
  Failure
Problems in Global:
! ERROR Unable to safely backup halconfig This archives contains
  unclosed entries.

- Failed to create a backup.
com.netflix.spinnaker.halyard.cli.services.v1.ExpectedDaemonFailureException: Failed to create a backup.
	at com.netflix.spinnaker.halyard.cli.services.v1.OperationHandler.get(OperationHandler.java:45)
	at com.netflix.spinnaker.halyard.cli.command.v1.backup.CreateBackupCommand.executeThis(CreateBackupCommand.java:50)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.safeExecuteThis(NestableCommand.java:181)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:129)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:132)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:132)
	at com.netflix.spinnaker.halyard.cli.Main.main(Main.java:47)
Caused by: java.lang.Exception: Unable to safely backup halconfig This archives contains unclosed entries.
	at com.netflix.spinnaker.halyard.backup.services.v1.BackupService.create(BackupService.java:79)
	at com.netflix.spinnaker.halyard.controllers.v1.BackupController.lambda$create$0(BackupController.java:46)
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:121)
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Throwable: This archives contains unclosed entries.
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:122)
	at com.netflix.spinnaker.halyard.backup.services.v1.BackupService.tarHalconfig(BackupService.java:143)
	at com.netflix.spinnaker.halyard.backup.services.v1.BackupService.create(BackupService.java:77)
	... 4 more`

**Comment by lwander** [comment]
The linked PR should fix the problem, however I can't reproduce. My guess is some file that had neither the directory or file bit set in the archive was leaving unclosed entries.

**Comment by lwander** [comment]
Reopening because github autoclosed this

**Comment by lwander** [comment]
Let's close this when you get a chance to test this. In the mean time, can you verify that there was a WARN message in your halyard logs /var/log/spinnaker/halyard/halyard.log indicating that there was an unknown filetype?

**Comment by bggpoort** [comment]
No WARN messages were found mentioning an unknown filetype

**Comment by bggpoort** [comment]
Today I've upgraded Halyard to version to 0.31.0-20170808194141. It appears Halyard isn't complaining about unclosed entries anymore. Backup is now breaking because it isn't able to access  files under .hal/default/staging/dependencies. These are generated by Spinnaker and have mode 600 (user:spinnaker, group:spinnaker). The Halyard daemon is running under the user id that installed Halyard.

**Comment by lwander** [comment]
Thanks!

**Comment by bggpoort** [comment]
Issue still exists with hal version 0.34.0.

**Comment by lwander** [comment]
Please retry when 0.35.0 is released. You will need to redeploy first (to have halyard assign correct permissions) before creating a backup.

**Comment by bggpoort** [comment]
@lwander As discussed this issue was probably part of my installation. I can confirm this issue doesn't exists on a fresh install so I suggest we close this ticket.
