### ISSUE TITLE
Azure Storage Authentication Error

### ISSUE THREAD

**Issue by rossedman** [spinnaker/halyard#626]
When I add my azure storage account to Spinnaker it validates, but when I try to deploy it does not and it gives me an Authentication error. 

```
com.netflix.spinnaker.halyard.core.error.v1.HalException: Failed to connect to the Azure storage account "$ACCOUNT_NAME": Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
	at com.netflix.spinnaker.halyard.core.problem.v1.ProblemSet.throwifSeverityExceeds(ProblemSet.java:102)
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:114)
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
	at java.lang.Thread.run(Thread.java:745)
```

Wondering how I can fix this? Have double checked my credentials and everything is correct.

**Comment by lwander** [comment]
@EricJizbaMSFT can you take a look at this?

**Comment by rossedman** [comment]
@lwander @EricJizbaMSFT would love to help anyway I can. I also received an Authentication Error when deploying to Azure Container Registry, but I'm guessing that's more of a Spinnaker issue.

**Comment by EricJizbaMSFT** [comment]
@rossedman It looks like your account is explicitly set to '$ACCOUNT_NAME', but Halyard doesn't know how to interpret a bash environment variable like that. Did you set the ACCOUNT_NAME environment variable _before_ running `hal config storage azs edit --storage-account-name $ACCOUNT_NAME ...`?

See here for more detail: https://www.spinnaker.io/setup/storage/azs/

**Comment by rossedman** [comment]
@EricJizbaMSFT Hey, sorry for the confusion. I did that just to remove personal details. I followed the Halyard instructions and tried multiple variations. I also thought it had to do with some unescaped characters in the storage key being used and tried regenerating those as well. I had no luck.

**Comment by rossedman** [comment]
@EricJizbaMSFT does the storage account resource group need to be named SpinnakerStorage?

**Comment by rossedman** [comment]
Just to clarify as well, I went into the ~/.hal/config file and ensured the values were correct before posting here so, yes, the environment variables were set correctly and Halyard accepted the values. It fails during the deploy command.

**Comment by rossedman** [comment]
@EricJizbaMSFT Follow up on this. I spun up a VM local and walked through all the steps for a local deployment exactly as stated in the documentation. It worked for a couple of deployments, then after an hour or so the Authorization quit working and I had to switch back to Redis. Nothing had changed in the `.hal` files besides some settings to proxy to Deck. 

The keys haven't changed and are still correct in the config file.

**Comment by EricJizbaMSFT** [comment]
@rossedman No the resource group name doesn't matter as long as you're consistent. I was hoping the ACCOUNT_NAME was the problem and would be an easy fix haha. Not sure what's going on - you'll have to ask @rguthriemsft for any further investigation

**Comment by rossedman** [comment]
@EricJizbaMSFT Thanks for following up.

**Comment by rossedman** [comment]
@EricJizbaMSFT @rguthriemsft Follow up to this. I believe something happened to Front50 in the 1.1.1 release. If I rollback to 1.1.0 Azure storage works fine. Also, I was trying to authenticate with ACR for my Docker Registry. I assumed it would work since it's a standard Docker V2 registry but the Auth piece must be different and cause other problems.

Can confirm Azure storage works if I use 1.1.0

**Comment by rossedman** [comment]
Going to close this for now, I saw Spinnaker 1.1.2 was released to adjust some Front50 pieces. Azure Storage is working for me 1.1.0. I think there was permission errors happening related to Front50.
