### ISSUE TITLE
S3 bucket versioning 

### ISSUE THREAD

**Issue by cristim** [spinnaker/halyard#647]
The S3 bucket created by the distributed setup should have versioning enabled in order to avoid accidental data loss and for backup purposes

**Comment by lwander** [comment]
For whoever can tackle this: the code lives in front50: https://github.com/spinnaker/front50/blob/master/front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java#L61-L78

**Comment by cristim** [comment]
I created a patch largely based on http://docs.aws.amazon.com/AmazonS3/latest/dev/manage-versioning-examples.html#manage-versioning-examples-java but I'm not sure how to test it.

This is the first time I've actually touched Java code in many years, so please bear with me :)

**Comment by lwander** [comment]
It LGTM, I would open a PR and we can see what the netflix team thinks

**Comment by cristim** [comment]
@lwander done, see https://github.com/spinnaker/front50/issues/259
