### ISSUE TITLE
artifactId for private docker repos

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/halyard#670]
I would like to propose a solution for a problem we are experiencing and would like to PR

artifactId can be set to a private docker repo, k8s wont have access to that repository if you dont provide imagePullSecrets to the container definitions. What I propose is modifying the following:
```
artifactId: gcr.io/private-repo/clouddriver:latest
```

To look like

```
artifact:
    artifactId: gcr.io/private-repo/clouddriver:latest
    imagePullSecret: private-repo-gcr-secret
```

where imagePullSecret would be a docker config secret type in kubernetes. The imagePullSecret would then define the imagePullSecret for the service's container definition.

I know that this section of the docs, https://www.spinnaker.io/reference/halyard/custom/#tweakable-service-settings and the service-settings file is 'user-beware' territory so I think we can still support artifactId at the top level, and maybe just introduce artifact and then define things for k8s further down below, or remove artifactId from the top level definition completely, in favor of an artifact section that can hold more information as needed for other platforms.

LMK your thoughts.

**Comment by lwander** [comment]
What do you think about instead having a 

```yaml
kubernetes:
  imagePullSecret: something-something
```

section? Artifacts exist across platforms, so pulling them into provider-specific sections makes the most sense to me.

**Comment by edwinavalos** [comment]
that makes sense, we can go with that, do you care our approach to this? If it is just kubernetes specific it won't need a generic implementation like deployment location needed.

**Comment by lwander** [comment]
Yup, go to town on this!

**Comment by axb59** [comment]
```
kubernetes:
  imagePullSecret: 
    - something-something 
    - something-something
```
This is a multi-item array so we are aiming to support multiple items in the specification
