### ISSUE TITLE
Halyard - adding docker repo with self signed cert fails

### ISSUE THREAD

**Issue by laurieodgers** [spinnaker/halyard#680]
I'm having some issues within the docker container mentioned at https://www.spinnaker.io/setup/install/halyard/

`docker run --name halyard --rm -v ~/.hal:/root/.hal gcr.io/spinnaker-marketplace/halyard:stable`

I am currently attempting to add a local docker repository (v2) which uses a self signed certificate:

```
hal config provider docker-registry account add staging-registry \
    --address localhost \
    --username user \
    --repositories "10.1.1.1:5000/test 10.1.1.1:5000/test2" \
    --password
```

results in the following error:
```
! ERROR Unable to reach repository:
  sun.security.validator.ValidatorException: PKIX path building failed:
  sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
  certification path to requested target.
```

Is there any way to disable SSL verification? Or any way that I can supply a truststore in order to get communication working between `hal` and our local docker repo?

I'm not sure if this is related, but our docker repo is v2 and supports the catalog endpoint (I have tested with curl) and omitting the --repositories flag results in the following error:
```
Problems in default.provider.dockerRegistry.staging-registry:
! ERROR Your docker registry has no repositories specified, and the
  registry's catalog is empty.
? Manually specify some repositories for this docker registry to
  index.
```

**Comment by lwander** [comment]
1. Self-signed certs: This doesn't work today because the underlying HTTP client needs to be hand-loaded with your custom certs. I don't have the time to implement this in the near future, but if anyone is interested: the relevant code lives here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy#L128. I'm guessing this will help: https://stackoverflow.com/questions/23103174/does-okhttp-support-accepting-self-signed-ssl-certs

2. Catalog: Have you checked that the catalog contains repos with your given credentials? Halyard complains about the empty catalog endpoint because when it comes time to deploy Spinnaker, not having any repositories to deploy images from is confusing. If it's not empty, what's the endpoint your catalog lives at?

**Comment by Spellchaser** [comment]
I believe I have the same kind of error. I'm trying to get Halyard working on a corp network (read firewalls and cert modifications). I've configured my proxies correctly but I'm pretty sure my corp is messing with SSL certs. I've seen something about loading BOMs from disk?

I've tried installing certs from gcr.io, dl.bintray.com, and storage.googleapis.com into the jks but it hasn't worked.
https://github.com/spinnaker/spinnaker/issues/1773
https://gist.github.com/anonymous/71293722aaf9ccdf50969d177923a06c

**Comment by podnov** [comment]
@laurieodgers Re: omitting the --repositories flag: looking at the code, I believe it's thinking the catalog is empty because of the SSL cert validation failure. The request is "failing silently" on the SSL cert validation, and then returning zero entries in the catalog.

I'm looking at implementing a --insecure-registry=[true|false] flag in spinnaker/clouddriver-docker and adding support to spinnaker/halyard

**Comment by githubvick** [comment]
Hi, I'm also just working on this and need this fix. Thanks a lot @podnov . Pls let us know when the fix is available and in what version.

**Comment by podnov** [comment]
@lwander Can I take you up on that offer to get this and spinnaker/clouddriver#1887 working together?

**Comment by pycaster** [comment]
@podnov : Is this change available and which version?

**Comment by podnov** [comment]
@pycaster Not yet, waiting on a review/merge.

**Comment by pycaster** [comment]
@podnov 

Meanwhile,

I thew the following in service-settings for clouddriver-bootstrap.yml to see which keystore is being used and imported my certs there using keytool,

```
env:
  SPRING_PROFILES_ACTIVE: bootstrap
  JAVA_OPTS: -Djavax.net.debug=all
```

```
keytool -importcert -file /usr/local/share/ca-certificates/Issuing_CA.crt -keystore $JAVA_HOME/lib/security/cacerts -trustcacerts -alias Issuing_CA
```
```
keytool -importcert -file /usr/local/share/ca-certificates/Root_CA.crt -alias Root_CA -keystore $JAVA_HOME/lib/security/cacerts -trustcacerts
```

I was expecting the service to the missing certs and move past the bug but this dint work for me either.

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_111-internal]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_111-internal]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_111-internal]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_111-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_111-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_111-internal]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[na:1.8.0_111-internal]
        ... 69 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_111-internal]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_111-internal]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_111-internal]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[na:1.8.0_111-internal]
        ... 75 common frames omitted
```

Is this expected to work at runtime?

**Comment by podnov** [comment]
@pycaster I haven't actually deployed hal/spinnaker successfully yet. I've been waiting on this fix to get back to it.  I'm probably not the best person to ask this question of.

**Comment by podnov** [comment]
Can confirm this has been fixed and added in halyard version-0.38.0.

**Comment by pycaster** [comment]
Worked for me. Thanks. Waiting for release of clouddriver.

https://github.com/spinnaker/clouddriver/pull/1887

**Comment by podnov** [comment]
@pycaster Haven't had a chance to confirm myself yet, but this should be in any recent 1.5.x release.
