### ISSUE TITLE
Installing Spinnaker in a specific Kubernetes namespace

### ISSUE THREAD

**Issue by wheleph** [spinnaker/halyard#682]
By default Spinnaker is installed in Kubernetes namespace `spinnaker` but I need to have a custom one.

To achieve that I created a separate kubectl context:
```
kubectl config set-context $(kubectl config current-context) --namespace=my-spinnaker
```

And then used it during the halyard setup:
```
hal config provider kubernetes account add spinnaker-k8s \
    --docker-registries gcr-eu \
    --context $(kubectl config current-context)
```

But unfortunately I still see that Spinnaker is installed into `spinnaker` namespace.

**Comment by lwander** [comment]
If the context informed where Spinnaker was installed it would always end up in default. Use `--location`: https://www.spinnaker.io/reference/halyard/commands/#hal-config-deploy-edit (sorry that's not exactly obvious).

**Comment by lwander** [comment]
The reason for the slightly generic term is that `location` goes across providers and informs where Spinnaker is installed for any `distributed` environment.

**Comment by wheleph** [comment]
`--location` works perfectly, thank you!
