### ISSUE TITLE
Not a supported operating system:  Debian

### ISSUE THREAD

**Issue by inmchfw** [spinnaker/halyard#689]
Hi everyone, I new to spinnaker. I am running halyard docker image on fedora 26. And I got a problem in the very last step when I want to do local installation. hal says ubuntu 14.4 is recommended. I am confused because isn't the halyard docker image a ubuntu 14.4?

![image](https://user-images.githubusercontent.com/22935688/30281188-a3428a42-9709-11e7-917b-2717a15ce6a6.png)

**Comment by lwander** [comment]
It is - but docker images don't have the necessary `apt` & upstart components to run Spinnaker. You'll need to install Halyard on a VM, or manage a k8s cluster (minikube might be a good idea here).

**Comment by inmchfw** [comment]
Thanks

**Comment by inmchfw** [comment]
![image](https://user-images.githubusercontent.com/22935688/30326772-84b15de8-97c1-11e7-86e8-798eadaf7c22.png)

**Comment by lwander** [comment]
If you have a VM, why not install halyard directly instead of using a docker container? That will solve this problem.

**Comment by christophetd** [comment]
@lwander What's the point of the docker container if the OS running inside isn't supported by Halyard? I thought it was provided because Halyard can't run on some Ubuntu versions (including 16.04 LTS, #279), but apparently that's not the case.

**Comment by lwander** [comment]
When you are managing a remote deployment of Spinnaker (into GKE, minikube, ...) and your local env isn't supported.

**Comment by christophetd** [comment]
I get the intention of the Docker image- but how does it help if the OS version running inside is not supported? Correct me if I'm wrong, but this container is not usable currently, right?

In my case: I'd like to deploy Spinnaker on a Kubernetes cluster. But as I'm running Ubuntu 16.04 LTS (not supported by Halyard), I tried making use of the Docker image, but it's unsupported as well.

**Comment by lwander** [comment]
The error you saw happens when you try to install Spinnaker to your local machine. If you (prior to `hal deploy apply`) configure your environment to be "distributed" you won't see that error. See https://www.spinnaker.io/setup/install/environment/

**Comment by christophetd** [comment]
Nope, the error mentioned in this issue appears when running the Docker container itself.

>  I am running halyard docker image on fedora 26
