### ISSUE TITLE
! Error Failed to connect to localhost/....:8064

### ISSUE THREAD

**Issue by inmchfw** [spinnaker/halyard#691]
Hi all,

I have just finished https://www.spinnaker.io/setup/install/halyard/#installation. When I do config edit, it fails. Any recommendations?

![image](https://user-images.githubusercontent.com/22935688/30325101-5b2b78e2-97bb-11e7-8a85-f20b6fd4d469.png)

Thanks

**Comment by lwander** [comment]
Notice the installation says the daemon never started. Can you share you /var/log/upstart/halyard logs, as well as /var/log/spinnaker/halyard/halyard.log?

**Comment by inmchfw** [comment]
@lwander , It went OK after I restart the VM.

I have shut down my VM. So when I open the machine to get the logs for you, I did not find anything in /var/log/upstart and had an empty log at /var/log/spinnaker/halyard/halyard.log. But instead, I run the same command `hal config deploy edit --type localdebian`, which no longer complain. Thanks for your attention.

**Comment by inmchfw** [comment]
@lwander , I got much further with VM image Ubuntu 14.04 Desktop LTS. Tried server version of 14.04, tried docker on top of Ubuntu 17.04 and fedora 26. None of them worked.

**Comment by inmchfw** [comment]
![image](https://user-images.githubusercontent.com/22935688/30335849-4c1d87b2-97db-11e7-8733-c4c64c174ec2.png)
