### ISSUE TITLE
Add port mappings for docker halyard container

### ISSUE THREAD

**Issue by neilhwatson** [spinnaker/halyard#698]
With only native support for Ubuntu the rest of us must use the docker container. Installing Spinnaker via halyard on k8s I end up having to use halyard connect to proxy to Spinnaker, but the Docker container doesn't account for this. I don't know what port are required to do it myself and I don't think you can bind the ports before they are running in the container. So proxying via the container may not be possible. In which case please support major Linux distros like Red Hat and Debian.

**Comment by lwander** [comment]
Good point - if I understood correctly this should do the trick: https://github.com/spinnaker/spinnaker.github.io/commit/e9510e2c080bce80f428680931f15d28501d472c
