### ISSUE TITLE
Installation of halyard over macOS doesn't work

### ISSUE THREAD

**Issue by kiril-dayradzhiev** [spinnaker/halyard#719]
I am triggering install of halyard using /install/osx/InstallHalyard.sh file and it files due to following issue:
Unable to access https://storage.googleapis.com/spinnaker-artifacts/halyard/$HALYARD_VERSION/osx/halyard.tar.gz archive. 
When I am trying to access 
https://storage.googleapis.com/spinnaker-artifacts/halyard/stable/osx/halyard.tar.gz I am receiving access denied. 

Workaround : use https://storage.googleapis.com/spinnaker-artifacts/halyard/$HALYARD_VERSION/debian/halyard.tar.gz

**Comment by lwander** [comment]
This is intentional, there is no stable release published for that installer.

**Comment by kiril-dayradzhiev** [comment]
At least the error message could be reworked

**Comment by lwander** [comment]
Sure, feel free to submit a PR
