### ISSUE TITLE
Make replica count settable via config

### ISSUE THREAD

**Issue by thomaschaaf** [spinnaker/halyard#725]
We have used halyard to setup spinnaker on kubernetes. We are using autoscaling intensely with our cluster. Currently all replica sets have a desired count of 1, which is not good if one node terminates.

If I am not mistaken it is currently hardcoded like this: https://github.com/spinnaker/halyard/blob/5795c82c8c8a31a324d3298cdcbe538b145c38ab/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java#L525

Is there a way to edit that number of orcas, fiats and gates we can have?

We also found https://github.com/spinnaker/halyard/blob/5795c82c8c8a31a324d3298cdcbe538b145c38ab/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java#L76 but did not find any reference what it actually does.

**Comment by edwinavalos** [comment]
Target is currently working on this, should be ready soon.

**Comment by edwinavalos** [comment]
We opened this issue to describe what behavior Target preferred, https://github.com/spinnaker/halyard/issues/736

We have a PR ready here:
https://github.com/spinnaker/halyard/pull/737 that should get merged soon.
