### ISSUE TITLE
Problem to indent the subcommands parameters

### ISSUE THREAD

**Issue by Luizm** [spinnaker/halyard#732]
When I'm configuring the security using hal.

```
hal --version
0.35.0-20171002204641

hal config security authn oauth2 edit \
    --client-id "XXX" \
    --client-secret "XXXX" \
    --provider "github"
```

 I recive the error:
```
Was passed main parameter '.' but no main parameter was defined
```

It's only happens when I indent the code, if a pass all parameters in the same line, it's works.

Am I doing something wrong?

**Comment by lwander** [comment]
`--client-secret` shouldn't be passed on the command line. Try leaving out the value, pass `--client-secret` as a flag, and then enter it via STDIN when prompted.
