### ISSUE TITLE
Restart hal instead of deploying everytime config changes

### ISSUE THREAD

**Issue by RTBathula** [spinnaker/halyard#742]
I feel need to have a feature like `hal deploy restart` instead of deploying with `hal deploy apply` every time we change some configuration.

**Comment by lwander** [comment]
Which environment are you deploying to?

**Comment by RTBathula** [comment]
I am running halyard in a VM(google cloud) and deployed all spinnaker things on kubernetes cluster(in google cloud). 
Problem is when I change some changes in configuration like add Jenkins Integration or Enable Slack, It is asking to do `hal deploy apply`  which is re deploying all spinnaker microservice components again in kubernetes cluster, also taking lot of time.

**Comment by lwander** [comment]
Your config should be versioned alongside your deployments - in order to properly facilitate rollbacks as well as correctly do "immutable infrastructure" your replica sets need to be redeployed. I know it's annoyingly slow, but it's the safest way to manage these deployments.

**Comment by RTBathula** [comment]
Okay Iwander, You can close this feature request then If that is the way it has to be.

**Comment by lwander** [comment]
Thanks
