### ISSUE TITLE
error from first_halyard_boot.sh

### ISSUE THREAD

**Issue by Jszuser** [spinnaker/halyard#760]
I got the following error message on a newly deployed spinnaker VM on GCE (from first_halyard_boot.sh)
```
10:52:50.524 [main] INFO com.netflix.spinnaker.halyard.cli.services.v1.ResponseUnwrapper - Message from task Add the my-gcr-account2 account: Running validation - Validating my-gcr-account2 with PublicServiceValidator
Problems in default.provider:
! ERROR Account "my-gcr-account2" appears more than once
? Change the name of the account in dockerRegistry
```
The Spinnaker VM is deployed according to:
https://console.cloud.google.com/launcher/details/click-to-deploy-images/spinnaker?q=spinnaker&project=ianatest-164415 
By deploying a second Spinnaker VM with gcr account name: "my-gcr-account2", I get the same error.

What could be wrong?

**Comment by lwander** [comment]
Is this with 0 modification to first_halyard_boot.sh? Where did my-gcr-account2 come from in the first attempt?

**Comment by Jszuser** [comment]
Hello Iwander, thanks for the quick answer. Yes. It is with 0 modification to first_halyard_boot.sh. "my-gcr-account2" come from the second VM. But the first VM has the some error. (By creating the Spinnaker VM in Google Cloud for the second time, I named gcr account name to "my-gcr-account2" instead of "my-gcr-account".)

**Comment by lwander** [comment]
My guess is that the install script is being run twice, not sure why that's happening yet. Are you rebooting the VM while it's starting up maybe? Or something similar?

**Comment by Jszuser** [comment]
Many thanks Iwander. You are right, the install script is being run twice. After removing one, it is ok now.
