### ISSUE TITLE
Hal and Ubuntu 14.04

### ISSUE THREAD

**Issue by ipeacocks** [spinnaker/halyard#766]
Of course you are good guys because you share your product. And I want to say thank you for that. 

But do you know that now is **2017**? I want to be polite but can't in this case.

**Comment by pycaster** [comment]
I am doubting this even works today unless someone proves me wrong.

**Comment by lwander** [comment]
https://gist.github.com/spinnaker-release/235774d2d17f3bd96d3ed6c446b065a4#spinnaker-160
