### ISSUE TITLE
Docker pull fails with "Access Denied"

### ISSUE THREAD

**Issue by mike10010100** [spinnaker/halyard#786]
Command:
`docker pull gcr.io/spinnaker-marketplace/halyard:stable`

Response:
`Error response from daemon: pull access denied for gcr.io/spinnaker-marketplace/halyard, repository does not exist or may require 'docker login'`

This seems to be a fresh issue today, as yesterday I was able to pull images freely from the registry.

**Comment by betandr** [comment]
See also https://github.com/spinnaker/spinnaker/issues/2165

**Comment by mike10010100** [comment]
Closing the issue as it seems the repo is back online.
