### ISSUE TITLE
Halyard seems to require running as root?

### ISSUE THREAD

**Issue by alertedsnake** [spinnaker/halyard#798]
Fresh install, just ran and apparently I need to run it as root?

```
$ hal -v
0.39.0-20180103211607

$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Problems in default.provider.aws.east1-dev01:
- WARNING No validation for the AWS provider has been
  implemented.

+ Preperation complete... deploying Spinnaker
+ Get current deployment
  Success
^ Apply deployment
. Apply deployment
- Apply deployment
^ Apply deployment
. Apply deployment
- Apply deployment
^ Apply deployment
. Apply deployment
- Apply deployment
^ Apply deployment
+ Apply deployment
  Success
+ Run `hal deploy connect` to connect to Spinnaker.
/home/michael/.hal/default/install.sh must be executed with root permissions; exiting
! ERROR Error encountered running script. See above output for more
  details.
```

I see in this script there's a bunch of stuff about installing a local redis (from a custom repo even), but nowhere do the docs say I need to be running hal as root.

**Comment by lwander** [comment]
It says right here you need root for local debian installations (apt-get requires root): https://www.spinnaker.io/setup/install/deploy/#deploy

**Comment by alertedsnake** [comment]
Ah!  That's a good clue - turns out I copied over my .hal directory from an aborted container attempt with a previous version and somehow the deployment environment config got converted from the Kubernetes target to LocalDebian.  Not sure how that happened, or why I didn't notice it when reviewing the config.  Thanks!

**Comment by lwander** [comment]
No problem! :)
