### ISSUE TITLE
Option for disabling "spinners"

### ISSUE THREAD

**Issue by bobbytables** [spinnaker/halyard#835]
We provision a box for halyard using Terraform + Remote provisioner scripts and the output for the logs is enormous because it prints a new line for each of the "spinners". It would be nice to turn off some of the "interactive" parts of Halyard for automation purposes.

**Comment by lwander** [comment]
You can run with `-q` to quite the "interactive" output, and with `--log=info` to still get individual messages on validation/deployment status.
