### ISSUE TITLE
Confusing upgrade instructions / versions

### ISSUE THREAD

**Issue by svenbovens** [spinnaker/halyard#843]
We received the message 

```
Problems in halconfig:
- WARNING There is a newer version of Halyard available (0.41.0),
  please update when possible
? sudo apt-get update && sudo apt-get upgrade spinnaker-halyard
```

After following above instructions (also mentioned on https://www.spinnaker.io/setup/install/halyard/) we got halyard version 0.30.0-110.

We're running on Ubuntu 14.04.5

Note that I found & executed the update-halyard in /usr/local/bin which seems to have upgraded halyard to 0.41.0-180212111030

I'm not sure if that's the correct approach/version though.

Did I do something wrong or do the upgrade instructions require an update?

**Comment by lwander** [comment]
Good catch, fix incoming

**Comment by svenbovens** [comment]
Thanks @lwander. Shouldn't the site https://www.spinnaker.io/setup/install/halyard/ be updated too?

**Comment by iniinikoski** [comment]
About this one:

```
sudo apt-get update && sudo apt-get upgrade spinnaker-halyard
```

Should it be instead:

```
sudo apt-get update && sudo apt-get install spinnaker-halyard
```

Otherwise it upgrades other packages than halyard also... Or is this the purpose of it?

**Comment by lwander** [comment]
right and right! will update

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/570

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/848
